In [0]:
import numpy as np
import pandas as pd

In [0]:
import warnings
warnings.filterwarnings('ignore')

In [0]:
train=pd.read_csv('/content/drive/My Drive/train_data.csv')
test=pd.read_csv('/content/drive/My Drive/test_data.csv')
sample_submission = pd.read_csv('/content/drive/My Drive/sample_submission.csv')

In [0]:
train=train.drop(columns=['id'])
test=test.drop(columns=['id'])

In [0]:
X_train=train.drop(columns=['price_range'])
y_train=train[['price_range']]
X_test=test

In [8]:
from sklearn.preprocessing import StandardScaler
X_train_scale=StandardScaler().fit_transform(X_train)
pd.DataFrame(X_train_scale).head()

0        1         2   ...        17        18        19
0 -0.976452  1.00143 -1.245224  ... -1.762263 -1.007169 -1.024588
1 -0.390618  1.00143 -1.245224  ...  0.567452 -1.007169  0.976002
2 -0.149926  1.00143  0.211077  ... -1.762263 -1.007169 -1.024588
3 -1.426045  1.00143  1.788737  ...  0.567452 -1.007169  0.976002
4 -0.099971  1.00143  0.939228  ...  0.567452 -1.007169 -1.024588

[5 rows x 20 columns]

#Logistic Regression

In [0]:
from sklearn.linear_model import LogisticRegression

In [11]:
from sklearn.model_selection import GridSearchCV
grid = {"C" : np.logspace(-3,3,7),"penalty" : ["l1","l2"]} #c = 1/ alpha
score = GridSearchCV(LogisticRegression(),grid).fit(X_train,y_train)


print(score.best_params_)
print(score.best_score_)

{'C': 0.1, 'penalty': 'l2'}
0.6421428571428571


In [0]:
lr = LogisticRegression(C=0.1,penalty = "l2", random_state=0) 
lr = lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,sample_submission['price_range']))

              precision    recall  f1-score   support

           0       0.20      0.23      0.21       144
           1       0.26      0.23      0.24       145
           2       0.27      0.26      0.26       145
           3       0.23      0.23      0.23       166

    accuracy                           0.24       600
   macro avg       0.24      0.24      0.24       600
weighted avg       0.24      0.24      0.24       600



In [14]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(LogisticRegression(),X_train,y_train,cv=5)
print(scores)
print(scores.mean()) 

[0.65357143 0.62857143 0.64642857 0.65       0.63214286]
0.6421428571428571


#SVM

In [0]:
from sklearn.svm import SVC

In [25]:
from sklearn.model_selection import GridSearchCV
grid = { "C" : np.logspace(-3,3,7) , "gamma" : ["scale", "auto"]  } 
score = GridSearchCV(SVC(),grid).fit(X_train,y_train)


print(score.best_params_)
print(score.best_score_)

{'C': 1000.0, 'gamma': 'scale'}
0.9650000000000001


In [0]:
svm = SVC(C=1000.0, kernel='linear',gamma = 'scale', random_state=0)
svm = svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)


In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,sample_submission['price_range']))

              precision    recall  f1-score   support

           0       0.22      0.24      0.23       150
           1       0.22      0.19      0.21       149
           2       0.28      0.25      0.26       154
           3       0.26      0.30      0.28       147

    accuracy                           0.24       600
   macro avg       0.24      0.25      0.24       600
weighted avg       0.25      0.24      0.24       600



In [19]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(SVC(),X_train,y_train,cv=5)
print(scores)
print(scores.mean()) 

[0.95       0.92142857 0.95357143 0.925      0.94285714]
0.9385714285714286


In [0]:
data = {'id' : sample_submission['id'],
        'price_range' : y_pred}
result = pd.DataFrame(data)
result.to_csv('/content/drive/My Drive/result_svm3.csv',index=False) 

#Random Forest Classifier


In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
from sklearn.model_selection import GridSearchCV
grid = {"n_estimators" : np.linspace(10,100,10).astype(np.int64),"criterion" : ["gini","entropy"]} 
score = GridSearchCV(RandomForestClassifier(),grid).fit(X_train,y_train)


print(score.best_params_)
print(score.best_score_)

{'criterion': 'entropy', 'n_estimators': 100}
0.865


In [0]:
forest = RandomForestClassifier(criterion='entropy',
                                n_estimators=100,
                                random_state=0)

forest = forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)

In [23]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(RandomForestClassifier(),X_train,y_train,cv=5)
print(scores)
print(scores.mean()) 

[0.875      0.825      0.88571429 0.86071429 0.86428571]
0.862142857142857


#KNN

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
from sklearn.model_selection import GridSearchCV
grid = {"metric" : ["minkowski","manhattan","euclidean"]} 
score = GridSearchCV(KNeighborsClassifier(),grid).fit(X_train,y_train)


print(score.best_params_)
print(score.best_score_)

{'metric': 'minkowski'}
0.9071428571428571


In [0]:
knn = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski',p=2, algorithm = 'auto')
knn = knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,sample_submission['price_range']))

              precision    recall  f1-score   support

           0       0.22      0.24      0.23       151
           1       0.23      0.20      0.22       150
           2       0.25      0.23      0.24       151
           3       0.25      0.28      0.26       148

    accuracy                           0.24       600
   macro avg       0.24      0.24      0.24       600
weighted avg       0.24      0.24      0.24       600



In [35]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(KNeighborsClassifier(),X_train,y_train,cv=5)
print(scores)
print(scores.mean()) 

[0.90357143 0.925      0.91071429 0.88571429 0.91071429]
0.9071428571428571


In [0]:
data = {'id' : sample_submission['id'],
        'price_range' : y_pred}
result = pd.DataFrame(data)
result.to_csv('/content/drive/My Drive/result_KNN.csv',index=False) 